version: '3.8'

services:
  jsonexcel-viewer:
    image: jsonexcel-viewer:v0.1.0
    ports:
      - '23333:23333'
    restart: unless-stopped
    networks:
      - analyzer_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  analyzer_network:
    name: analyzer_network
    driver: bridge
